version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.typelevel:cats-effect_2.12
    versions:
    - 3.0-8096649
    - 3.0.1
    - 3.0.2
  - dependency-name: co.fs2:fs2-core_2.12
    versions:
    - 3.0-5795280
    - 3.0.1
  - dependency-name: co.fs2:fs2-io_2.12
    versions:
    - 3.0-5795280
    - 3.0.1
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "4.0"
  - dependency-name: org.owasp:dependency-check-maven
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
  - dependency-name: org.scala-lang:scala-library
    versions:
    - 2.13.4
  - dependency-name: net.alchim31.maven:scala-maven-plugin
    versions:
    - 4.4.0
